"""Retrospective modeling routines."""

from plasmid_priority.modeling.design_matrix_cache import (
    DesignMatrixCache,
    DesignMatrixCacheKey,
)
from plasmid_priority.modeling.discovery_contract import (
    DiscoveryInputContract,
    build_discovery_input_contract,
    discovery_model_names,
    validate_discovery_input_contract,
)
from plasmid_priority.modeling.experiment_gates import (
    ConfigCandidate,
    ExperimentAcceptanceGates,
    HonestModelResult,
    compute_honest_result,
    evaluate_experiment_gates,
    interpret_gain,
)
from plasmid_priority.modeling.fold_plan import FoldPlan
from plasmid_priority.modeling.module_a import (
    ABLATION_MODEL_NAMES,
    CONSERVATIVE_MODEL_NAME,
    CORE_MODEL_NAMES,
    FEATURE_PROVENANCE_REGISTRY,
    MODULE_A_FEATURE_SETS,
    MODULE_A_MODEL_TRACKS,
    NOVELTY_SPECIALIST_FEATURES,
    NOVELTY_SPECIALIST_FIT_CONFIG,
    RESEARCH_MODEL_NAMES,
    annotate_knownness_metadata,
    assert_feature_columns_present,
    build_cmim_feature_selection_table,
    build_coefficient_stability_table,
    build_feature_dropout_audit,
    build_logistic_convergence_audit,
    build_standardized_coefficient_table,
    evaluate_feature_columns,
    evaluate_model_name,
    fit_feature_columns_predictions,
    fit_full_model_predictions,
    fit_predict_model_holdout,
    get_conservative_model_name,
    get_feature_track,
    get_governance_model_name,
    get_model_track,
    get_module_a_model_names,
    get_official_model_names,
    get_primary_model_name,
    get_research_models_by_track,
    run_module_a,
    select_cmim_features,
)
from plasmid_priority.modeling.module_a_support import (
    PRIMARY_MODEL_NAME,
    assert_all_discovery_safe,
    get_active_model_names,
)
from plasmid_priority.modeling.preprocessing import (
    build_design_matrix_cache_key,
    prepare_feature_matrices,
)

__all__ = [
    "ABLATION_MODEL_NAMES",
    "CORE_MODEL_NAMES",
    "CONSERVATIVE_MODEL_NAME",
    "ConfigCandidate",
    "DiscoveryInputContract",
    "DesignMatrixCache",
    "DesignMatrixCacheKey",
    "ExperimentAcceptanceGates",
    "FEATURE_PROVENANCE_REGISTRY",
    "FoldPlan",
    "HonestModelResult",
    "MODULE_A_FEATURE_SETS",
    "MODULE_A_MODEL_TRACKS",
    "NOVELTY_SPECIALIST_FEATURES",
    "NOVELTY_SPECIALIST_FIT_CONFIG",
    "PRIMARY_MODEL_NAME",
    "RESEARCH_MODEL_NAMES",
    "assert_all_discovery_safe",
    "assert_feature_columns_present",
    "annotate_knownness_metadata",
    "build_discovery_input_contract",
    "build_coefficient_stability_table",
    "build_cmim_feature_selection_table",
    "build_feature_dropout_audit",
    "build_logistic_convergence_audit",
    "build_standardized_coefficient_table",
    "build_design_matrix_cache_key",
    "compute_honest_result",
    "discovery_model_names",
    "evaluate_experiment_gates",
    "evaluate_feature_columns",
    "evaluate_model_name",
    "fit_feature_columns_predictions",
    "fit_full_model_predictions",
    "fit_predict_model_holdout",
    "get_active_model_names",
    "get_conservative_model_name",
    "get_feature_track",
    "get_governance_model_name",
    "get_model_track",
    "get_module_a_model_names",
    "get_official_model_names",
    "get_primary_model_name",
    "get_research_models_by_track",
    "interpret_gain",
    "run_module_a",
    "prepare_feature_matrices",
    "select_cmim_features",
    "validate_discovery_input_contract",
]
