"""Shared country constants for geography and harmonization modules.

This module provides a single source of truth for country definitions to avoid
circular dependencies between low-level utilities and higher-level harmonization.
"""

from __future__ import annotations

# Canonical country mappings: canonical name -> set of recognized aliases
# This is the authoritative source used by both harmonize/records.py and utils/geography.py
COUNTRY_ALIAS_GROUPS: dict[str, set[str]] = {
    "Afghanistan": {"AFGHANISTAN"},
    "Albania": {"ALBANIA"},
    "Algeria": {"ALGERIA"},
    "Andorra": {"ANDORRA"},
    "Angola": {"ANGOLA"},
    "Antigua and Barbuda": {"ANTIGUA AND BARBUDA"},
    "Argentina": {"ARGENTINA"},
    "Armenia": {"ARMENIA"},
    "Aruba": {"ARUBA"},
    "Australia": {"AUSTRALIA"},
    "Austria": {"AUSTRIA"},
    "Azerbaijan": {"AZERBAIJAN"},
    "Bahamas": {"BAHAMAS", "THE BAHAMAS"},
    "Bahrain": {"BAHRAIN"},
    "Bangladesh": {"BANGLADESH"},
    "Barbados": {"BARBADOS"},
    "Belarus": {"BELARUS"},
    "Belgium": {"BELGIUM"},
    "Belize": {"BELIZE"},
    "Benin": {"BENIN"},
    "Bermuda": {"BERMUDA"},
    "Bhutan": {"BHUTAN"},
    "Bolivia": {"BOLIVIA", "BOLIVIA PLURINATIONAL STATE OF"},
    "Bosnia and Herzegovina": {"BOSNIA AND HERZEGOVINA"},
    "Botswana": {"BOTSWANA"},
    "Brazil": {"BRAZIL"},
    "Brunei": {"BRUNEI", "BRUNEI DARUSSALAM"},
    "Bulgaria": {"BULGARIA"},
    "Burkina Faso": {"BURKINA FASO"},
    "Burundi": {"BURUNDI"},
    "Cambodia": {"CAMBODIA"},
    "Cameroon": {"CAMEROON"},
    "Canada": {"CANADA"},
    "Cape Verde": {"CAPE VERDE", "CABO VERDE"},
    "Cayman Islands": {"CAYMAN ISLANDS"},
    "Central African Republic": {"CENTRAL AFRICAN REPUBLIC"},
    "Chad": {"CHAD"},
    "Chile": {"CHILE"},
    "China": {
        "CHINA",
        "PEOPLES REPUBLIC OF CHINA",
        "PEOPLE S REPUBLIC OF CHINA",
        "PR CHINA",
        "P R CHINA",
    },
    "Colombia": {"COLOMBIA"},
    "Comoros": {"COMOROS"},
    "Costa Rica": {"COSTA RICA"},
    "Croatia": {"CROATIA"},
    "Cuba": {"CUBA"},
    "Curacao": {"CURACAO", "CURAÇAO"},
    "Cyprus": {"CYPRUS"},
    "Czech Republic": {"CZECH REPUBLIC", "CZECHIA"},
    "Democratic Republic of the Congo": {
        "DEMOCRATIC REPUBLIC OF THE CONGO",
        "DRC",
        "DR CONGO",
        "D R CONGO",
    },
    "Denmark": {"DENMARK"},
    "Djibouti": {"DJIBOUTI"},
    "Dominica": {"DOMINICA"},
    "Dominican Republic": {"DOMINICAN REPUBLIC"},
    "Ecuador": {"ECUADOR"},
    "Egypt": {"EGYPT"},
    "El Salvador": {"EL SALVADOR"},
    "Equatorial Guinea": {"EQUATORIAL GUINEA"},
    "Eritrea": {"ERITREA"},
    "Estonia": {"ESTONIA"},
    "Eswatini": {"ESWATINI", "SWAZILAND"},
    "Ethiopia": {"ETHIOPIA"},
    "Faroe Islands": {"FAROE ISLANDS"},
    "Fiji": {"FIJI"},
    "Finland": {"FINLAND"},
    "France": {"FRANCE"},
    "French Guiana": {"FRENCH GUIANA"},
    "French Polynesia": {"FRENCH POLYNESIA"},
    "Gabon": {"GABON"},
    "Gambia": {"GAMBIA", "THE GAMBIA"},
    "Georgia": {"GEORGIA"},
    "Germany": {"GERMANY"},
    "Ghana": {"GHANA"},
    "Gibraltar": {"GIBRALTAR"},
    "Greece": {"GREECE"},
    "Greenland": {"GREENLAND"},
    "Grenada": {"GRENADA"},
    "Guadeloupe": {"GUADELOUPE"},
    "Guam": {"GUAM"},
    "Guatemala": {"GUATEMALA"},
    "Guernsey": {"GUERNSEY"},
    "Guinea": {"GUINEA"},
    "Guinea-Bissau": {"GUINEA BISSAU"},
    "Guyana": {"GUYANA"},
    "Haiti": {"HAITI"},
    "Honduras": {"HONDURAS"},
    "Hong Kong": {"HONG KONG", "HONG KONG SAR"},
    "Hungary": {"HUNGARY"},
    "Iceland": {"ICELAND"},
    "India": {"INDIA"},
    "Indonesia": {"INDONESIA"},
    "Iran": {"IRAN", "IRAN ISLAMIC REPUBLIC OF"},
    "Iraq": {"IRAQ"},
    "Ireland": {"IRELAND", "REPUBLIC OF IRELAND"},
    "Isle of Man": {"ISLE OF MAN"},
    "Israel": {"ISRAEL"},
    "Italy": {"ITALY"},
    "Ivory Coast": {"IVORY COAST", "COTE D IVOIRE", "COTE DIVOIRE"},
    "Jamaica": {"JAMAICA"},
    "Japan": {"JAPAN"},
    "Jersey": {"JERSEY"},
    "Jordan": {"JORDAN"},
    "Kazakhstan": {"KAZAKHSTAN"},
    "Kenya": {"KENYA"},
    "Kosovo": {"KOSOVO"},
    "Kuwait": {"KUWAIT"},
    "Kyrgyzstan": {"KYRGYZSTAN"},
    "Laos": {"LAOS", "LAO PDR", "LAO PEOPLE S DEMOCRATIC REPUBLIC"},
    "Latvia": {"LATVIA"},
    "Lebanon": {"LEBANON"},
    "Lesotho": {"LESOTHO"},
    "Liberia": {"LIBERIA"},
    "Libya": {"LIBYA"},
    "Liechtenstein": {"LIECHTENSTEIN"},
    "Lithuania": {"LITHUANIA"},
    "Luxembourg": {"LUXEMBOURG"},
    "Macau": {"MACAU", "MACAO"},
    "Madagascar": {"MADAGASCAR"},
    "Malawi": {"MALAWI"},
    "Malaysia": {"MALAYSIA"},
    "Maldives": {"MALDIVES"},
    "Mali": {"MALI"},
    "Malta": {"MALTA"},
    "Martinique": {"MARTINIQUE"},
    "Mauritania": {"MAURITANIA"},
    "Mauritius": {"MAURITIUS"},
    "Mayotte": {"MAYOTTE"},
    "Mexico": {"MEXICO"},
    "Moldova": {"MOLDOVA", "REPUBLIC OF MOLDOVA"},
    "Monaco": {"MONACO"},
    "Mongolia": {"MONGOLIA"},
    "Montenegro": {"MONTENEGRO"},
    "Morocco": {"MOROCCO"},
    "Mozambique": {"MOZAMBIQUE"},
    "Myanmar": {"MYANMAR", "BURMA"},
    "Namibia": {"NAMIBIA"},
    "Nepal": {"NEPAL"},
    "Netherlands": {"NETHERLANDS", "THE NETHERLANDS"},
    "New Caledonia": {"NEW CALEDONIA"},
    "New Zealand": {"NEW ZEALAND"},
    "Nicaragua": {"NICARAGUA"},
    "Niger": {"NIGER"},
    "Nigeria": {"NIGERIA"},
    "North Korea": {"NORTH KOREA", "DPRK", "D P R K", "DEMOCRATIC PEOPLE S REPUBLIC OF KOREA"},
    "North Macedonia": {"NORTH MACEDONIA", "MACEDONIA", "REPUBLIC OF MACEDONIA"},
    "Norway": {"NORWAY"},
    "Oman": {"OMAN"},
    "Pakistan": {"PAKISTAN"},
    "Palestine": {"PALESTINE", "STATE OF PALESTINE", "WEST BANK", "GAZA"},
    "Panama": {"PANAMA"},
    "Papua New Guinea": {"PAPUA NEW GUINEA"},
    "Paraguay": {"PARAGUAY"},
    "Peru": {"PERU"},
    "Philippines": {"PHILIPPINES", "THE PHILIPPINES"},
    "Poland": {"POLAND"},
    "Portugal": {"PORTUGAL"},
    "Puerto Rico": {"PUERTO RICO"},
    "Qatar": {"QATAR"},
    "Republic of the Congo": {"REPUBLIC OF THE CONGO", "CONGO BRAZZAVILLE"},
    "Reunion": {"REUNION", "RÉUNION"},
    "Romania": {"ROMANIA"},
    "Russia": {"RUSSIA", "RUSSIAN FEDERATION"},
    "Rwanda": {"RWANDA"},
    "Saint Kitts and Nevis": {"SAINT KITTS AND NEVIS"},
    "Saint Lucia": {"SAINT LUCIA"},
    "Saint Vincent and the Grenadines": {"SAINT VINCENT AND THE GRENADINES"},
    "Samoa": {"SAMOA"},
    "San Marino": {"SAN MARINO"},
    "Sao Tome and Principe": {"SAO TOME AND PRINCIPE"},
    "Saudi Arabia": {"SAUDI ARABIA"},
    "Senegal": {"SENEGAL"},
    "Serbia": {"SERBIA"},
    "Seychelles": {"SEYCHELLES"},
    "Sierra Leone": {"SIERRA LEONE"},
    "Singapore": {"SINGAPORE"},
    "Slovakia": {"SLOVAKIA"},
    "Slovenia": {"SLOVENIA"},
    "Somalia": {"SOMALIA"},
    "South Africa": {"SOUTH AFRICA"},
    "South Korea": {"SOUTH KOREA", "KOREA", "KOREA REPUBLIC OF", "REPUBLIC OF KOREA"},
    "South Sudan": {"SOUTH SUDAN"},
    "Spain": {"SPAIN"},
    "Sri Lanka": {"SRI LANKA"},
    "Sudan": {"SUDAN"},
    "Suriname": {"SURINAME"},
    "Sweden": {"SWEDEN"},
    "Switzerland": {"SWITZERLAND"},
    "Syria": {"SYRIA", "SYRIAN ARAB REPUBLIC"},
    "Taiwan": {"TAIWAN", "TAIWAN ROC", "TAIWAN R O C", "REPUBLIC OF CHINA"},
    "Tajikistan": {"TAJIKISTAN"},
    "Tanzania": {"TANZANIA", "UNITED REPUBLIC OF TANZANIA"},
    "Thailand": {"THAILAND"},
    "Togo": {"TOGO"},
    "Trinidad and Tobago": {"TRINIDAD AND TOBAGO"},
    "Tunisia": {"TUNISIA"},
    "Turkey": {"TURKEY", "TURKIYE", "TÜRKIYE", "REPUBLIC OF TURKEY"},
    "Turkmenistan": {"TURKMENISTAN"},
    "Uganda": {"UGANDA"},
    "Ukraine": {"UKRAINE"},
    "United Arab Emirates": {"UNITED ARAB EMIRATES", "UAE", "U A E"},
    "UK": {
        "UNITED KINGDOM",
        "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND",
        "UK",
        "U K",
        "GREAT BRITAIN",
        "ENGLAND",
        "SCOTLAND",
        "WALES",
        "NORTHERN IRELAND",
    },
    "USA": {
        "UNITED STATES",
        "UNITED STATES OF AMERICA",
        "USA",
        "U S A",
        "US",
        "U S",
        "U.S.A",
        "U.S.",
    },
    "Uruguay": {"URUGUAY"},
    "Uzbekistan": {"UZBEKISTAN"},
    "Venezuela": {"VENEZUELA", "VENEZUELA BOLIVARIAN REPUBLIC OF"},
    "Vietnam": {"VIETNAM", "VIET NAM"},
    "Virgin Islands, U.S.": {"US VIRGIN ISLANDS", "U S VIRGIN ISLANDS", "VIRGIN ISLANDS U S"},
    "Yemen": {"YEMEN"},
    "Zambia": {"ZAMBIA"},
    "Zimbabwe": {"ZIMBABWE"},
}
